spring:
  application:
    name: shopping backend
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8090