spring:
  application:
    name: payment gateway
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_payment_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8070